enum class GamePhase {
    SELECT_LEAGUE,
    PLAYING,
    LEAGUE_WINNER,
    LEAGUE_RANKING,


    SUPERLEAGUE_PLAYING,   // 🆕 8 vár egymás ellen
    SUPERLEAGUE_WINNER,
    SUPERLEAGUE_RANKING,
   USER_SUPERLEAGUE_RANKING,
    CASTLE_INFO

}

